name: fireflutter
description: A free, open source, rapid development package for creating Social apps based on Firebase.
version: 0.0.9
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  rxdart: ^0.24.1

  firebase_core: "0.5.0+1"
  firebase_auth: "^0.18.1+2"
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: "^0.3.0"
  cloud_firestore: "^0.14.1+3"
  firebase_storage: "^5.0.0-dev.3"
  firebase_messaging: ^7.0.3

  sign_in_with_apple: ^2.5.4
  crypto: ^2.1.5

  dio: ^3.0.10

  image_picker: ^0.6.7+12
  permission_handler: ^5.0.1+1
  flutter_image_compress: ^0.7.0

  path_provider: ^1.6.21

  algolia: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
