name: fireflutter
description: A free, open source, complete, rapid development package for creating Social apps, Community apps, Shopping mall apps, and much more based on Firebase.
version: 0.0.34
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  rxdart: ^0.24.1

  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  flutter_facebook_auth: ^1.0.1
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.0.1
  firebase_messaging: ^7.0.3

  sign_in_with_apple: ^2.5.4
  crypto: ^2.1.5

  dio: ^3.0.10

  image_picker: ^0.6.7+14
  permission_handler: ^5.0.1+1

  flutter_image_compress: ^0.7.0

  path_provider: ^1.6.24

  algolia: ^0.1.7
  merge_map: ^1.0.2

  location: ^3.1.0
  geoflutterfire: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
