name: fireflutter
description: A rapid development package for creating Social apps based on Firebase.
version: 0.0.4
homepage: https://github.com/thruthesky/fireflutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.24.1

  firebase_core: "0.5.0+1"
  firebase_auth: "^0.18.1+2"
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: "^0.3.0"
  cloud_firestore: "^0.14.1+3"
  firebase_storage: "^5.0.0-dev.3"
  firebase_messaging: ^7.0.3

  jiffy: ^3.0.1
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
